Repository Shuudy/b3-svelma, pull requests merged in 2025-05, with the labels that each got.

#3 feat(filters): add genre and year filtering with UI integration and state management
  src/components/Filter.svelte
  src/components/FilterBar.svelte
  src/components/Mask.svelte
  src/routes/+page.svelte
Labels: enhancement

#2 chore: setup Netlify deployment workflow
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  svelte.config.js
Labels: cd

#4 docs: update README.md with project description and setup guide
  README.md
Labels: documentation

#5 fix: ensure overflow-y is set to auto for filterbar
  src/assets/css/_filterbar.scss
Labels: bug

#6 feat: improve actor card and title
  src/assets/css/_actors.scss
  src/routes/films/[id]/+page.svelte
  src/routes/personnes/[id]/+page.svelte
Labels: enhancement

#10 feat: improve homepage metadata and handle missing person data
  src/components/LogoHeader.svelte
  src/routes/+page.svelte
  src/routes/personnes/[id]/+page.svelte
Labels: enhancement

#11 refactor(accessibility): improve semantic structure and keyboard navigation
  src/app.html
  src/assets/css/_filterbar.scss
  src/assets/css/_reset.scss
  src/components/ActorCard.svelte
  src/components/Filter.svelte
  src/components/FilterBar.svelte
  src/components/LogoHeader.svelte
  src/components/Mask.svelte
  src/components/MovieCard.svelte
  src/components/MovieDetails.svelte
  src/components/Navbar.svelte
  src/components/Pagination.svelte
  src/components/SearchBar.svelte
  src/routes/+page.svelte
  src/routes/films/[id]/+page.svelte
  src/routes/personnes/[id]/+page.svelte
Labels: enhancement

#12 feat: improve accessibility on homepage
  src/components/FilterBar.svelte
  src/routes/+page.svelte
Labels: enhancement

#14 fix: move Pagination component rendering inside conditional block for…
  src/routes/+page.svelte
Labels: bug
